spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_platform?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: naQRLdDPbGv2j7PX_
  data:
    redis:
      host: localhost
      port: 6379
      password: PmEpfRjpBnTN6CgW

minio:
  endpoint: http://127.0.0.1:9001 #内网地址
  public: http://127.0.0.1:9001  #外网访问地址
  accessKey: admin
  secretKey: 3fBSt6AkgFuD77D6
  bucketName: box-im
  imagePath: image
  filePath: file
  videoPath: video

webrtc:
  max-channel: 9 # 多人通话最大通道数量，最大不能超过16,建议值:4,9,16
  iceServers:   #coturn配置
    - urls: stun:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV
    - urls: turn:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV

